import Header from "../components/Header"
import Footer from "../components/Footer"
import Image from "next/image"
import Head from "next/head"
import Link from "next/link"
import Mailer from "../components/mailer"
import React, { useRef } from 'react';
import emailjs from '@emailjs/browser';

const headerMsg = "Let\'s talk about your next project"

export default function Contact(props) {

  const service_id = props.emailjs_service_id
  const template_id = props.emailjs_template_id
  const public_id = props.emailjs_public_key

  const form = useRef();

  const sendEmail = (e) => {
    e.preventDefault();

    emailjs.sendForm(service_id,template_id, form.current,public_id)
      .then((result) => {
          console.log(result.text);
          if(result.text === "OK") {
            console.log("Do something")
          }
      }, (error) => {
          console.log(error.text);
      });
  };

 return(
  <>
  <Head>
  <title>Contact | duris.io</title>
  <meta name="contact form for duris.io" content="Generated by create-t3-app" />
</Head>  
 <Header/>
 <main>
 <div className="text-4xl text-center text-gray-500 border-b mx-auto">
  <h1 className="py-10 pb-4">Contact</h1>
  <h2 className=" text-lg py-4 pb-10 font-thin">{headerMsg}</h2>
  
  </div>
<div className="grid grid-cols-1 sm:grid-cols-2 mx-auto float-none">
  <div className=" float-right m-10">
  <Image 
      src="https://ik.imagekit.io/zhmk2wx4u/Screen_Shot_2022-08-09_at_4.53.43_PM_WT1r4A7ov.png?ik-sdk-version=javascript-1.4.3&updatedAt=1660078449773" 
      width={630} height={480} 
      alt="showcase website" 
      objectFit="cover"
      className="bg-gray-100 rounded-[40px] shadow-sm float-right inline-block" 
      />      
  </div>
  <div>
{/* <div className=" p-6">
  <h2 className=" text-xl text-gray-500">Email:</h2>
  <span className=" text-blue-500 text-2xl inline-block mt-2 hover:text-blue-300">
  <Link href="mailto:ross@duris.io">hello@duris.io</Link>
  </span>
</div>
<div className="mt-4  p-6">
  <h2 className=" text-xl text-gray-500">Phone:</h2>
  <span className=" text-blue-500 text-2xl inline-block mt-2 hover:text-blue-300"><Link href="#">(614) 394-2530</Link></span>
</div> */}
  <div className="p-8 mx-auto w-full">      
        <form ref={form} onSubmit={sendEmail}>
          <label className="mt-1 inline-block ">Name</label>
          <input type="text" name="user_name" className="border w-full rounded-md"/>
          <br/>
          <label className="mt-1 inline-block ">Email</label>
          <input type="email" name="user_email" className="border w-full rounded-md"/>
          <br/>
          <label className="mt-1 inline-block ">Message</label>
          <textarea name="message" rows="4" className="border w-full rounded-md"/>
          <br/>
          <input type="submit" value="Send" className="bg-blue-400 p-2 px-4 rounded-lg text-white w-full mt-4 cursor-pointer"/>
        </form>
      </div>

  </div>

  </div>
 </main>
 <Footer />
 </>
 )
}

export async function getServerSideProps() {

  const emailjs_service_id = process.env.YOUR_SERVICE_ID
  const emailjs_template_id = process.env.YOUR_TEMPLATE_ID
  const emailjs_public_key = process.env.YOUR_PUBLIC_KEY


  return {
    props: {
      emailjs_service_id: emailjs_service_id,
      emailjs_template_id: emailjs_template_id,
      emailjs_public_key: emailjs_public_key,
    }
  }
}
